### ISSUE TITLE
Please remove upper bound on test.requires setuptools dependency

### ISSUE THREAD

**Issue by sfc-gh-tmonk** [AnacondaRecipes/snowflake-telemetry-python-feedstock#4]
In an upcoming sprint, we are requesting version 0.4.0 of this package that bumps the OpenTelemetry dependencies among other changes.

While making the changes for version 0.4.0, please also remove the upper bound on the setuptools dependency listed in meta.yaml's test.requires section. That is, this line:

```yaml
    - setuptools >=40,<66
```

should be:

```yaml
    - setuptools >=40
```

**Comment by lorepirri** [comment]
resolution: removed the `setuptools` dependency from the requirements of the tests in #5 .
